### ISSUE TITLE
404 Error for the APT3 operational flows

### ISSUE THREAD

**Issue by clane00289** [mitre-attack/attack-evals#30]
https://attackevals.mitre-engenuity.org/apt3/operational-flow.html is presenting a 404 error

**Comment by JeffJLi** [comment]
Hi clane00289,

Thanks for bringing this to our attention! You're getting a 404 error because the urls are case-sensitive. The correct url is [https://attackevals.mitre-engenuity.org/APT3/operational-flow.html](https://attackevals.mitre-engenuity.org/APT3/operational-flow.html) (Upper-case APT3).

I've fixed the broken link on the APT3 Overview page that used lower-case "apt3", but if you have the link bookmarked, you will have to change your bookmark link from "apt3" to "APT3".

Hope that helps!

**Comment by clane00289** [comment]
Thank you.  You guys rock!
